version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: mortgage-ai-postgres
    environment:
      POSTGRES_DB: mortgage_db
      POSTGRES_USER: mortgage_user
      POSTGRES_PASSWORD: mortgage_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./docker/postgres/02-dutch-mortgage-schema.sql:/docker-entrypoint-initdb.d/02-dutch-mortgage-schema.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mortgage_user -d mortgage_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: mortgage-ai-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API Service
  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: mortgage-ai-backend
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REQUIRE_AUTH=${REQUIRE_AUTH:-false}
      - DATABASE_URL=postgresql://mortgage_user:mortgage_pass@postgres:5432/mortgage_db
      - REDIS_URL=redis://redis:6379
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app/backend
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: mortgage-ai-frontend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3000
      - REACT_APP_REQUIRE_AUTH=${REQUIRE_AUTH:-false}
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    depends_on:
      - backend
    networks:
      - mortgage-ai-network
    restart: unless-stopped

  # Nginx Reverse Proxy with automatic port conflict resolution
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: mortgage-ai-nginx
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
    depends_on:
      - backend
      - frontend
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Python AI Agents Service
  ai-agents:
    build:
      context: .
      dockerfile: docker/ai-agents.Dockerfile
    container_name: mortgage-ai-agents
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://mortgage_user:mortgage_pass@postgres:5432/mortgage_db
      - REDIS_URL=redis://redis:6379
      # OpenCV headless environment variables
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - OPENCV_LOG_LEVEL=ERROR
    env_file: .env
    volumes:
      - ./backend/agents:/app/agents
      - ./models:/app/models
    ports:
      - "${AGENTS_PORT:-8003}:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Dutch Market Data Service - Handles AFM regulations, BKR, NHG data
  dutch-market-data:
    build:
      context: .
      dockerfile: docker/dutch-market-data.Dockerfile
    container_name: mortgage-ai-dutch-data
    environment:
      - AFM_REGULATION_FEED_URL=${AFM_REGULATION_FEED_URL}
      - AFM_API_KEY=${AFM_API_KEY}
      - BKR_API_URL=${BKR_API_URL}
      - BKR_API_KEY=${BKR_API_KEY}
      - NHG_VALIDATION_URL=${NHG_VALIDATION_URL}
      - NHG_API_KEY=${NHG_API_KEY}
      - PROPERTY_VALUATION_API_URL=${PROPERTY_VALUATION_API_URL}
      - PROPERTY_VALUATION_API_KEY=${PROPERTY_VALUATION_API_KEY}
      - DATABASE_URL=postgresql://mortgage_user:mortgage_pass@postgres:5432/mortgage_db
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mortgage_db
      - DB_USER=mortgage_user
      - DB_PASSWORD=mortgage_pass
      - NODE_ENV=production
      - DUTCH_DATA_PORT=8001
    env_file: .env
    volumes:
      - ./backend:/app/backend:ro
      - ./logs:/app/logs
    ports:
      - "${DUTCH_DATA_PORT:-8001}:8001"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Lender Integration Service - Handles Stater, Quion, ING, Rabobank, ABN AMRO
  lender-integration:
    build:
      context: .
      dockerfile: docker/lender-integration.Dockerfile
    container_name: mortgage-ai-lender-integration
    environment:
      - STATER_API_URL=${STATER_API_URL}
      - STATER_API_KEY=${STATER_API_KEY}
      - QUION_API_URL=${QUION_API_URL}
      - QUION_API_KEY=${QUION_API_KEY}
      - ING_API_URL=${ING_API_URL}
      - ING_API_KEY=${ING_API_KEY}
      - RABOBANK_API_URL=${RABOBANK_API_URL}
      - RABOBANK_API_KEY=${RABOBANK_API_KEY}
      - ABN_AMRO_API_URL=${ABN_AMRO_API_URL}
      - ABN_AMRO_API_KEY=${ABN_AMRO_API_KEY}
      - DATABASE_URL=postgresql://mortgage_user:mortgage_pass@postgres:5432/mortgage_db
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - LENDER_PORT=8002
    env_file: .env
    volumes:
      - ./backend:/app/backend:ro
      - ./logs:/app/logs
      - ./uploads:/app/uploads:ro
    ports:
      - "${LENDER_PORT:-8002}:8002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      dutch-market-data:
        condition: service_healthy
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AFM Compliance Monitor - Real-time AFM compliance monitoring and reporting
  afm-monitor:
    build:
      context: .
      dockerfile: docker/afm-monitor.Dockerfile
    container_name: mortgage-ai-afm-monitor
    environment:
      - AFM_AUDIT_WEBHOOK_URL=${AFM_AUDIT_WEBHOOK_URL}
      - COMPLIANCE_ALERT_EMAIL=${COMPLIANCE_ALERT_EMAIL}
      - AFM_REGULATION_FEED_URL=${AFM_REGULATION_FEED_URL}
      - AFM_API_KEY=${AFM_API_KEY}
      - DATABASE_URL=postgresql://mortgage_user:mortgage_pass@postgres:5432/mortgage_db
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mortgage_db
      - DB_USER=mortgage_user
      - DB_PASSWORD=mortgage_pass
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_EMAIL=${FROM_EMAIL}
      - NODE_ENV=production
      - AFM_MONITOR_PORT=8004
    env_file: .env
    volumes:
      - ./backend:/app/backend:ro
      - ./logs:/app/logs
      - ./compliance-reports:/app/reports
      - ./compliance-reports:/app/compliance-reports
    ports:
      - "${AFM_MONITOR_PORT:-8004}:8004"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Chat WebSocket Service - Real-time conversational AI for mortgage advisory
  chat-websocket:
    build:
      context: .
      dockerfile: docker/chat-websocket.Dockerfile
    container_name: mortgage-ai-chat-websocket
    environment:
      - DATABASE_URL=postgresql://mortgage_user:mortgage_pass@postgres:5432/mortgage_db
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=mortgage_db
      - DB_USER=mortgage_user
      - DB_PASSWORD=mortgage_pass
      - AGENTS_API_URL=http://ai-agents:8000
      - NODE_ENV=production
      - CHAT_WEBSOCKET_PORT=8005
    env_file: .env
    volumes:
      - ./backend:/app/backend:ro
      - ./logs:/app/logs
    ports:
      - "${CHAT_WEBSOCKET_PORT:-8005}:8005"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      ai-agents:
        condition: service_healthy
    networks:
      - mortgage-ai-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  mortgage-ai-network:
    driver: bridge
